version: '3'
services:
  db :
    image: mysql:8
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: mydb
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress